[package]
name = "cs4310_proj2_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.38"
env_logger = "0.11.8"
fuse = "0.3.1"
fuser = "0.15.1"
libc = "0.2.172"
pkg-config = "0.3.32"
time = "0.3.41"

[build-dependencies]
cc = "1.0"
bindgen = "0.71.1"
